name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew :sample:compileKotlinIosSimulatorArm64
